USE daohang;

CREATE TABLE IF NOT EXISTS site_data (
    id INT PRIMARY KEY AUTO_INCREMENT,
    data_key VARCHAR(50) NOT NULL UNIQUE,
    data_value LONGTEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backups (
    id INT PRIMARY KEY AUTO_INCREMENT,
    data LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);